---
version: '2'
services:
  prometheus:
    # Directory where docker file is present, and a custom prometheus will be build
    build: ./prometheus
    image: prometheus
    ports:
        - '9090:9090'
    hostname: prometheus
    container_name: prometheus
