spring:
  application:
    name: SimpleMart
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql : true
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/ecart
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    whitelabel:
      enabled: false
    
custom:
  validation:
    character:
      maxSize:
        fifteen: Size shouldn't exceed more than 15 characters
    email:
      format: Improper Email format

user:
  order:
    history:
      days: 31      
      
connection:
  exchange:
    review:
      url: http://localhost:8081/reviews/product/
